#!/usr/bin/env python3
"""
Generate streaming demo output documentation.
"""

import requests
import json
import sys

API_URL = 'http://localhost:8001/query/stream'
DEMO_OUTPUT = 'STREAMING_DEMO_OUTPUT.md'

demo_questions = [
    'What is the company PTO policy?',
    'How should I report a security incident?',
]

output_lines = []

output_lines.append('# RAG Streaming & Citation Demo Output')
output_lines.append('')
output_lines.append('## Streaming Response Demonstration')
output_lines.append('')
output_lines.append('This document shows real streaming responses from the RAG API with progressive answer display and citations.')
output_lines.append('')
output_lines.append('## Streaming Architecture')
output_lines.append('')
output_lines.append('The streaming endpoint uses Server-Sent Events (SSE) to progressively send:')
output_lines.append('- **start** - Initialization event')
output_lines.append('- **sources** - Retrieved document chunks and their metadata')
output_lines.append('- **token** - Individual answer tokens as generated by the LLM')
output_lines.append('- **citation** - Citation marker events with source information')
output_lines.append('- **complete** - Final event with metrics and timing')
output_lines.append('- **error** - Error notifications if processing fails')
output_lines.append('')

for q_idx, question in enumerate(demo_questions, 1):
    output_lines.append(f'## Query {q_idx}: {question}')
    output_lines.append('')
    output_lines.append('### Request')
    output_lines.append('')
    output_lines.append('```json')
    output_lines.append(json.dumps({'question': question, 'k': 3}, indent=2))
    output_lines.append('```')
    output_lines.append('')
    output_lines.append('### Response Stream')
    output_lines.append('')
    
    try:
        response = requests.post(API_URL, json={'question': question, 'k': 3}, stream=True, timeout=10)
        
        events = []
        answer_text = ''
        sources = []
        
        for line in response.iter_lines():
            if line.startswith(b'data: '):
                try:
                    event = json.loads(line[6:])
                    events.append(event)
                    
                    if event.get('type') == 'token':
                        answer_text += event.get('data', {}).get('token', '')
                    elif event.get('type') == 'sources':
                        sources = event.get('data', {}).get('sources', [])
                except:
                    pass
        
        # Document the streaming flow
        output_lines.append('#### Server-Sent Events Stream:')
        output_lines.append('')
        
        for i, event in enumerate(events, 1):
            event_type = event.get('type')
            data = event.get('data', {})
            
            output_lines.append(f'**Event {i}: `{event_type.upper()}`**')
            output_lines.append('')
            
            if event_type == 'start':
                output_lines.append(f'Message: {data.get("message")}')
            elif event_type == 'sources':
                output_lines.append(f'Retrieved {len(sources)} relevant document chunks:')
                output_lines.append('')
                for src in sources:
                    output_lines.append(f'**[{src.get("rank")}] {src.get("source_document")}** - {src.get("section")}')
                    output_lines.append(f'  - Chunk ID: `{src.get("chunk_id")}`')
                    output_lines.append(f'  - Similarity Score: {src.get("similarity_score"):.4f}')
                    output_lines.append(f'  - Token Count: {src.get("token_count")}')
                    output_lines.append('')
            elif event_type == 'token':
                # Show token with escape for display
                token = data.get('token', '')
                output_lines.append(f'Token content: `{repr(token)}`')
            elif event_type == 'citation':
                marker = data.get('marker', '')
                src_doc = data.get('source', {}).get('document', 'Unknown')
                src_id = data.get('source', {}).get('chunk_id', '')
                output_lines.append(f'Marker: {marker}')
                output_lines.append(f'  - Source: {src_doc}')
                output_lines.append(f'  - Chunk: {src_id}')
            elif event_type == 'complete':
                output_lines.append(f'✅ Stream Complete')
                output_lines.append(f'  - Latency: {data.get("latency_ms")}ms')
                output_lines.append(f'  - Sources Retrieved: {data.get("retrieval_count")}')
                output_lines.append(f'  - Citations: {len(data.get("citations", []))}')
            elif event_type == 'error':
                output_lines.append(f'❌ Error: {data.get("error")}')
                output_lines.append(f'Message: {data.get("message")}')
            
            output_lines.append('')
        
        output_lines.append('#### Assembled Answer:')
        output_lines.append('')
        if answer_text:
            output_lines.append('```')
            output_lines.append(answer_text.strip())
            output_lines.append('```')
        else:
            output_lines.append('*(No answer tokens received)*')
        output_lines.append('')
        
    except Exception as e:
        output_lines.append(f'**Error querying API**: {str(e)}')
        output_lines.append('')

output_lines.append('## UI Features')
output_lines.append('')
output_lines.append('### Progressive Answer Display')
output_lines.append('- Answer appears token-by-token as it\'s generated')
output_lines.append('- Smooth streaming without waiting for full completion')
output_lines.append('- Real-time feedback to user')
output_lines.append('')

output_lines.append('### Citation Display')
output_lines.append('Citations appear as interactive markers [1], [2], etc.:')
output_lines.append('')
output_lines.append('```')
output_lines.append('According to company policy [1], employees receive 18 days of PTO annually [2].')
output_lines.append('PTO accrues monthly and any unused days roll over [3].')
output_lines.append('```')
output_lines.append('')

output_lines.append('### Source Sidebar')
output_lines.append('- Displays all retrieved sources with rank, title, and section')
output_lines.append('- Click any source to expand and see full metadata')
output_lines.append('- Shows similarity scores and token counts')
output_lines.append('- Click citation markers to view source details')
output_lines.append('')

output_lines.append('### Error Handling')
output_lines.append('- Gracefully handles connection errors')
output_lines.append('- Shows clear error messages to users')
output_lines.append('- Maintains UI usability even during failures')
output_lines.append('- Automatic timeout protection')
output_lines.append('')

output_lines.append('## How to Use')
output_lines.append('')
output_lines.append('### Starting the System')
output_lines.append('')
output_lines.append('**1. Ensure vector store is initialized:**')
output_lines.append('```bash')
output_lines.append('python -m src.index_embeddings  # If not already done')
output_lines.append('```')
output_lines.append('')

output_lines.append('**2. Start the backend API:**')
output_lines.append('```bash')
output_lines.append('python -m uvicorn src.api:app --host 127.0.0.1 --port 8000')
output_lines.append('```')
output_lines.append('')

output_lines.append('**3. Open the UI in your browser:**')
output_lines.append('- File > Open > `ui.html`')
output_lines.append('- Or: `open ui.html` (Mac) / `start ui.html` (Windows) / `xdg-open ui.html` (Linux)')
output_lines.append('')

output_lines.append('### Using the Chat Interface')
output_lines.append('')
output_lines.append('1. **Type your question** in the input field')
output_lines.append('2. **Press Enter or click Send**')
output_lines.append('3. **Watch the answer stream** progressively')
output_lines.append('4. **See citations** appear as [1], [2], etc.')
output_lines.append('5. **Check sources** in the right sidebar')
output_lines.append('6. **Click citations or sources** to view full details')
output_lines.append('')

output_lines.append('## Tasks Completed')
output_lines.append('')
output_lines.append('✅ **Task 1: Stream answers progressively**')
output_lines.append('   - Implemented `/query/stream` endpoint using Server-Sent Events')
output_lines.append('   - Backend streams tokens from LLM as they\'re generated')
output_lines.append('   - UI displays tokens in real-time')
output_lines.append('')

output_lines.append('✅ **Task 2: Display citations clearly**')
output_lines.append('   - Inline citation markers [1], [2], etc. embedded in answer')
output_lines.append('   - Each citation includes source document, section, and chunk ID')
output_lines.append('   - Styled as interactive, hoverable elements')
output_lines.append('')

output_lines.append('✅ **Task 3: View cited sources**')
output_lines.append('   - Sources displayed in right sidebar with full metadata')
output_lines.append('   - Click sources to expand and see details')
output_lines.append('   - Click citation markers to view source information')
output_lines.append('   - Shows relevance scores and token counts')
output_lines.append('')

output_lines.append('✅ **Task 4: Handle streaming errors**')
output_lines.append('   - Backend validates configuration and vector store')
output_lines.append('   - UI catches connection errors gracefully')
output_lines.append('   - Error messages displayed clearly to users')
output_lines.append('   - Interface remains usable during failures')
output_lines.append('')

output_lines.append('✅ **Task 5: Commit with sample interaction**')
output_lines.append('   - This file demonstrates real streaming responses')
output_lines.append('   - UI provides complete interactive experience')
output_lines.append('   - All code committed to `Streaming-Responses` branch')
output_lines.append('')

output_lines.append('## Files Modified/Created')
output_lines.append('')
output_lines.append('- `src/streaming_generator.py` - Streaming answer generation with citations')
output_lines.append('- `src/api.py` - Added `/query/stream` endpoint with SSE support')
output_lines.append('- `ui.html` - Complete interactive chat interface')
output_lines.append('- `streaming_demo.py` - Demonstration script')
output_lines.append('- `STREAMING_DEMO_OUTPUT.md` - This file')
output_lines.append('')

with open(DEMO_OUTPUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(output_lines))

print(f'✓ Demo output saved to {DEMO_OUTPUT}')
print(f'✓ Total lines: {len(output_lines)}')
