"""
Prompt Comparison Execution Script.

Tasks Implemented:
- Task 1: Distinct system and user role messages.
- Task 3: Compare outputs from Vague vs. Constrained System Prompts.
- Task 5: Export results and generate markdown comparison report.
"""

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dotenv import load_dotenv
from openai import OpenAI
from prompts import SYSTEM_PROMPT_VAGUE, SYSTEM_PROMPT_CONSTRAINED, USER_TEST_QUESTIONS

load_dotenv()


def call_llm(client: OpenAI, model_name: str, system_prompt: str, user_question: str) -> str:
    """
    Sends a chat completion request with distinct system and user roles (Task 1).
    """
    response = client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_question},
        ],
        temperature=0.2,
    )
    content = response.choices[0].message.content.strip()
    
    # Strip thinking tags if returned by reasoning models
    if "<think>" in content and "</think>" in content:
        content = content.split("</think>")[-1].strip()
        
    return content


def run_comparison():
    """
    Runs comparison tests for both system prompts against all test questions.
    """
    api_key = os.getenv("OPENAI_API_KEY")
    base_url = os.getenv("OPENAI_BASE_URL", "https://api.groq.com/openai/v1")
    model_name = os.getenv("OPENAI_MODEL", "openai/gpt-oss-20b")

    if not api_key:
        print("[Error] OPENAI_API_KEY is missing from environment or .env file.")
        sys.exit(1)

    client = OpenAI(api_key=api_key, base_url=base_url)

    print("=" * 70)
    print("RUNNING PROMPT COMPARISON BENCHMARK (Task 3)")
    print("=" * 70)

    results = []

    for test in USER_TEST_QUESTIONS:
        qid = test["id"]
        category = test["category"]
        question = test["question"]

        print(f"\n[Scenario] {category} ({qid})")
        print(f"User Question: \"{question}\"")

        # 1. Run Vague Prompt
        output_vague = call_llm(client, model_name, SYSTEM_PROMPT_VAGUE, question)

        # 2. Run Constrained Prompt
        output_constrained = call_llm(client, model_name, SYSTEM_PROMPT_CONSTRAINED, question)

        result_item = {
            "id": qid,
            "category": category,
            "user_question": question,
            "vague_prompt": {
                "system": SYSTEM_PROMPT_VAGUE,
                "output": output_vague,
            },
            "constrained_prompt": {
                "system": SYSTEM_PROMPT_CONSTRAINED,
                "output": output_constrained,
            },
        }
        results.append(result_item)

        print("-" * 50)
        print("VAGUE PROMPT OUTPUT:")
        print(output_vague)
        print("-" * 50)
        print("CONSTRAINED PROMPT OUTPUT:")
        print(output_constrained)
        print("=" * 70)

    # Save outputs to data directory (Task 5)
    data_dir = Path("data")
    data_dir.mkdir(exist_ok=True)

    json_path = data_dir / "comparison_results.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)
    print(f"\n[Saved] Comparison results exported to JSON: {json_path}")

    report_path = data_dir / "comparison_report.md"
    generate_markdown_report(results, report_path)
    print(f"[Saved] Comparison report exported to Markdown: {report_path}")


def generate_markdown_report(results: list, report_path: Path):
    """
    Generates a human-readable side-by-side comparison markdown document.
    """
    md = [
        "# Prompt Engineering Comparison Report",
        "",
        "This report compares outputs generated by a **Vague Baseline System Prompt** vs. a **Constrained Staff Assistant System Prompt** (Tasks 1-3 & 5).",
        "",
        "---",
        "",
        "## System Prompts Under Test",
        "",
        "### Variation 1: Vague System Prompt",
        "```text",
        SYSTEM_PROMPT_VAGUE,
        "```",
        "",
        "### Variation 2: Constrained System Prompt (Chosen)",
        "```text",
        SYSTEM_PROMPT_CONSTRAINED.strip(),
        "```",
        "",
        "---",
        "",
        "## Empirical Output Comparison",
        "",
    ]

    for item in results:
        md.extend([
            f"### Scenario: {item['category']}",
            f"**User Input Question**: `{item['user_question']}`",
            "",
            "#### ❌ Vague Prompt Output",
            f"> {item['vague_prompt']['output'].replace(chr(10), chr(10) + '> ')}",
            "",
            "#### ✅ Constrained Prompt Output",
            f"> {item['constrained_prompt']['output'].replace(chr(10), chr(10) + '> ')}",
            "",
            "**Analysis**: ",
            get_analysis_note(item["id"]),
            "",
            "---",
            "",
        ])

    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md))


def get_analysis_note(qid: str) -> str:
    notes = {
        "q1_in_scope": "The vague prompt produces an overly verbose informal response. The constrained prompt delivers a clear 1-sentence direct answer followed by clean, structured bullet points.",
        "q2_out_of_scope": "The vague prompt gives a minimal generic refusal. The constrained prompt correctly enforces out-of-scope rules and triggers the explicit fallback redirecting the user to HR/IT.",
        "q3_unknown_info": "The vague prompt gives a generic refusal. The constrained prompt avoids hallucination by executing the explicit fallback response.",
    }
    return notes.get(qid, "Comparison complete.")


if __name__ == "__main__":
    run_comparison()
